version: '3.8'

services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:h2:mem:collect-dev
      - DATABASE_USER=sa
      - DATABASE_PWD=password
      - JWT_SECRET=api
