version: '3.8'

services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=${PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PWD=${DATABASE_PWD}
      - JWT_SECRET=${JWT_SECRET}
