services:

  db:
    container_name: mysql
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s    # Intervalo entre as verificações de saúde
      timeout: 5s      # Tempo de espera para a verificação
      retries: 5

  api:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:h2:mem:collect-dev
      - DATABASE_USER=userdev
      - DATABASE_PWD=password
      - JWT_SECRET=api