services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:h2:mem:collect-dev
      - DATABASE_USER=user
      - DATABASE_PWD=password
      - JWT_SECRET=api

  mysql:
    image: mysql
    environment:
      MYSQL_USERNAME: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
