version: '3.8'

services:

  api:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=${PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PWD=${DATABASE_PWD}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
    volumes:
      - pgdata:/var/lib/postgresql/data